server:
  port: 28060

spring:
  application:
    name: application-zuul
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://10.108.10.58:9411/

  rabbitmq:
    host: 10.108.10.17
    username: admin
    password: admin

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            defaultZone: http://localhost:8761/eureka/

# Disable Hystrix timeout globally (for all services)
# hystrix.command.default.execution.timeout.enabled: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
#hystrix.command.service-a.execution.timeout.enabled: false

# Disable Hystrix timeout for a single service
#hystrix.command.<serviceName>.execution.timeout.enabled: false

# Increase the Hystrix timeout to 60s (globally)
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

# Increase the Hystrix timeout to 60s (per service)
#hystrix.command.<serviceName>.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 180000
  ConnectTimeout: 180001
  
  
  
  
  
zuul:
  routes:
    sys:
      path: /sys/**
      stripPrefix: false
      serviceId: crm-auth
    role:
      path: /role/**
      stripPrefix: false
      serviceId: crm-auth
    org:
      path: /org/**
      stripPrefix: false
      serviceId: crm-auth

    auth:
      path: /auth/**
      stripPrefix: false
      serviceId: crm-auth

    user:
      path: /user/**
      stripPrefix: false
      serviceId: crm-auth
      customSensitiveHeaders: true
    log:
      path: /log/**
      stripPrefix: false
      serviceId: crm-auth
    dict:
      path: /dict/**
      stripPrefix: false
      serviceId: crm-auth
    business:
      path: /ids/**
      stripPrefix: false
      serviceId: crm-business
    
endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true

timestamp.validate.limit: 180